global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: ${SMTP_TO}
        from: ${SMTP_FROM}
        smarthost: ${SMTP_SMARTHOST}
        auth_username: ${SMTP_AUTH_USERNAME}
        auth_identity: ${SMTP_AUTH_IDENTITY}
        auth_password: ${SMTP_AUTH_PASSWORD}
        require_tls: true