services:
  nginx:
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - client
      - server
    networks:
      - webpong

  client:
    image: client:latest
    container_name: client
    build:
      context: ./Client
    volumes:
      - /app/node_modules
    env_file:
      - ./env/client.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - webpong

  server:
    image: server:latest
    container_name: server
    build:
      context: ./Server
    env_file:
      - ./env/api.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - webpong
    depends_on:
      - client

  prometheus:
    image: prom/prometheus:latest
    build:
      context: ./prometheus
    restart: unless-stopped
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=https://e3r8p4.1337.ma/prometheus'
      - '--web.route-prefix=/'
    networks:
      - webpong
    depends_on:
      - server
      - node-exporter
      - cadvisor
      - alertmanager

  alertmanager:
    image: prom/alertmanager:latest
    build:
      context: ./alertmanager
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./alertmanager/config:/etc/alertmanager
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=https://e3r8p4.1337.ma/alertmanager'
      - '--web.route-prefix=/'
    networks:
      - webpong

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    env_file:
      - ./env/grafana.env
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - webpong
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    pid: "host"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - webpong

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --docker_only=true
      - --housekeeping_interval=10s
    restart: unless-stopped
    networks:
      - webpong


networks:
  webpong:
    driver: bridge

volumes:
  grafana-storage:
  alertmanager-data:
